# .github/workflows/build.yml
name: build-appimage
on:
  push:
    branches: ["main"]
    tags: ["v*"]
  pull_request: {}

jobs:
  build:
    strategy:
      matrix:
        os: 
          - ubuntu-20.04  # GLIBC 2.31 (RHEL 8/9 compat)
          - ubuntu-24.04  # GLIBC 2.38 (neuere Systeme)
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential cmake ninja-build \
            qt6-base-dev qt6-declarative-dev qt6-tools-dev \
            qt6-qmltooling-plugins qml6-module-qtquick-controls \
            libgl1-mesa-dev patchelf zsync wget curl

      - name: Configure & build
        run: |
          cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -G Ninja
          cmake --build build -j

      - name: Package AppImage
        run: |
          chmod +x packaging/make-appimage.sh
          OS_SUFFIX=$(echo ${{ matrix.os }} | sed 's/ubuntu-/u/') \
            ./packaging/make-appimage.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: appimage-${{ matrix.os }}
          path: dist/*.AppImage